
- name: criando os usuarios padroes para todas as maquinas
  user:
   name: "{{item.nome}}"
   password: "{{item.senha}}"
   state: "{{item.estado}}"
   home: "{{item.casa}}"
  with_items:
   - { nome: lucas, senha: '$1$mxWiQYNW$dfD6586EkPauvtVR66EdQ.', estado: present, casa: /srv/lucas } 
   - { nome: developer, senha: '$1$mxWiQYNW$dfD6586EkPauvtVR66EdQ.', estado: present, casa: /srv/developer } 
   - { nome: devops, senha: '$1$mxWiQYNW$dfD6586EkPauvtVR66EdQ.', estado: present, casa: /srv/devops } 
