---

- name: exercicio
  hosts: all
  vars:
   - seunome: lucas
  tasks:
   - name: criando meu usuario no sistema
     user:
      name: "{{item}}"
     with_items:
      - "{{seunome}}"
      - developer
      - devops

   - name: instalando pacotes necessarios
     package:
      name:
       - htop
       - vim
       - cowsay
       - figlet

   - name: copiando arquivo devops
     file:
      path: /srv/devops
      state: touch

   - name: colocando conteudo no arquivo
     blockinfile:
      path: /srv/devops
      block: |
        sou devops
        na 4linux

   - name: copiando arquivo index para a devops
     file:
      path: /srv/index
      state: touch
     when: ansible_hostname == "devops"

   - name: colocando conteudo no arquivo
     blockinfile:
      path: /srv/index
      block: |
        sou devops
     when: ansible_hostname == "devops"
