---
# tasks file for pre-docker

- name: garantindo os pacotes principais
  package: 
   name:
    - docker-ce
    - nginx
    - python-pip

- name: instalando o docker-py
  pip:
   name: docker-py

- name: garantindo os servicos nginx e docker iniciados
  service:
   name: "{{item}}"
   state: started
  with_items:
   - nginx
   - docker

